# Generated by Django 4.2.3 on 2023-07-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='dayscount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
