# Generated by Django 4.2.3 on 2023-07-18 14:56

from django.db import migrations, models
import enums.work_type


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_remove_month_daynumber_day_day_of_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('work_time', models.IntegerField()),
                ('work_type', models.CharField(choices=[(enums.work_type.WorkType['ON_SITE'], 'ON_SITE'), (enums.work_type.WorkType['REMOTE'], 'REMOTE')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
